### PR TITLE
Build breaker identification notebook

### PR DESCRIPTION
**Pull request by CermakM**
The notebook demonstrates the usage of the new thoth-build-analysers library.

Signed-off-by: Marek Cermak <macermak@redhat.com>

new file:   notebooks/development/Build Breaker Identification.ipynb

### CODE REVIEW

**Review by goern — COMMENTED** [review]
LGTM

**Comment by CermakM** [comment]
Could I please get an acceptance confirmation on this one? It must have been forgotten somehow. I am not able to merge it otherwise.

**Comment by CermakM** [comment]
regate

**Review by goern — APPROVED** [review]

**Comment by CermakM** [comment]
Thanks!

**Pull request merged**
